=== helenamartins81/PRI2020/TPC3/pr.dtd
<?xml version="1.0" encoding="UTF-8"?>



<!ELEMENT projRecord (title, dados, workteam, abstract, deliverables) >

<!ELEMENT title (#PCDATA) >

<!ELEMENT dados (key_name, title, subtitle*, begin_date, end_date, supervisor) >
<!ELEMENT key_name (#PCDATA) >
<!ELEMENT begin_date (#PCDATA) >
<!ELEMENT end_date (#PCDATA) >
<!ELEMENT subtitle (#PCDATA) >
<!ELEMENT supervisor (#PCDATA) >
<!ATTLIST supervisor
            href CDATA #REQUIRED>

<!ELEMENT  workteam (elemento+) >
<!ELEMENT elemento (nome, email) >
<!ELEMENT nome (#PCDATA) >
<!ELEMENT email (#PCDATA) >


<!ELEMENT abstract (paragrafos+) >
<!ELEMENT paragrafos (frases+) >
<!ELEMENT frases (#PCDATA|bold|italic|ref)* >
<!ELEMENT bold (#PCDATA) >
<!ELEMENT italic (#PCDATA) >



<!ELEMENT deliverables (ref+) >
<!ELEMENT ref (#PCDATA) >
<!ATTLIST ref
            href CDATA #REQUIRED>

=== helenamartins81/PRI2020/TPC3/pr.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE projRecord SYSTEM "pr.dtd">
<projRecord>
    <title>Arqueossítios do Noroeste Português</title>
    <dados>
        <key_name>PRI_TP2</key_name>
        <title>Stylesheets XSL</title>
        <subtitle>TPC3 de PRI sobre stylesheets</subtitle>
        <begin_date>26-10-2020</begin_date>
        <end_date>2-11-2020</end_date>
        <supervisor href="http://www4.di.uminho.pt/~jcr/">José Carlos Ramalho></supervisor>
    </dados>
    <workteam>
        <elemento>
            <nome>Helena Poças Martins</nome>
            <email>a82500@alunos.uminho.pt</email>
        </elemento>
    </workteam>
    <abstract>
        <paragrafos>
            <frases>No terceiro TPC da cadeira de Processamento e Reconhecimento de Informação foi solicitada a criação de uma stylesheet XSL de modo a ser criado um website sobre os arqueossítios do noroeste português, dados que se encontram num ficheiro XML.</frases>
            <frases>O website é constituido por um índice que nos redireciona para a página HTML de cada arqueossítio escolhido.</frases>
            <frases>Além disso, também foi criado o DTD do ficheiro XML dos arqueossítios.</frases>
        </paragrafos>
    </abstract>
    <deliverables>
        <ref href="https://github.com/helenamartins81/PRI2020/blob/main/TPC3/arq.dtd">DTD do XML dos Arqueossítios</ref>
        <ref href="https://github.com/helenamartins81/PRI2020/blob/main/TPC3/arq.xml">XML dos Arqueossítios</ref>
        <ref href="https://github.com/helenamartins81/PRI2020/blob/main/TPC3/arq.xsl">XSL do XML dos Arqueossítios</ref>
        <ref href="https://github.com/helenamartins81/PRI2020/blob/main/TPC3/pr.dtd">DTD do Project Record</ref>
        <ref href="https://github.com/helenamartins81/PRI2020/blob/main/TPC3/pr.xml">XML do Project Record</ref>
        
    </deliverables>
</projRecord>

=== helenamartins81/PRI2020/TPC2/tp2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE projRecord SYSTEM "PR.dtd">
<projRecord>
    <title>Project Record</title>
    <dados>
        <key_name>PRI_TP2</key_name>
        <title>DTDs</title>
        <subtitle>TPC2 de PRI sobre DTDs</subtitle>
        <begin_date>19-10-2020</begin_date>
        <end_date>26-10-10</end_date>
        <supervisor href="http://www4.di.uminho.pt/~jcr/">José Carlos Ramalho</supervisor>
    </dados>
    <workteam>
        <elemento>
            <nome>Helena Poças Martins</nome>
            <email>a82500@alunos.uminho.pt</email>
        </elemento>
    </workteam>
    <abstract>
        <paragrafos>
            <frases>No segundo TPC da cadeira de Processamento e Reconhecimento de Informação foi solicitado aos alunos a criação de um DTD, que definisse um Project Record, e o respetivo ficheiro XML.</frases>
            <frases>Além disso, foram respondidas algumas questões sobre arqueossítios, usando <bold>XPath</bold>, cujo enunciado se encontra em <ref href="http://www4.di.uminho.pt/~jcr/AULAS/didac/RepFichas/site/fichas/f2.html#e2"> documentos</ref></frases>
        </paragrafos>
    </abstract>
    <deliverables>
        <ref href=""></ref>
    </deliverables>
</projRecord>
